name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
    - name: Install dependencies (apt)
      run: sudo apt-get install -y libsodium-dev libavahi-compat-libdnssd-dev
    - name: Install dependencies (gem)
      run: bundle install
    - name: Run tests
      run: bundle exec rspec
